# This file is an automatically generated pypref preferences file. 

__pypref_version__ = '3.1.0' 

##########################################################################################
###################################### PREFERENCES #######################################
preferences = {}
preferences['XnatUrl']   = 'http://10.1.1.20'
preferences['ProjId']    = 'NCITA_TEST'
preferences['SubjLabel'] = 'TCGA-BB-A5HY'
preferences['RR1']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '4', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 4'}
preferences['RR2']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '10', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 10'}
preferences['RR3']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 5'}
preferences['RR4']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '11', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 11'}
preferences['RR5']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '14', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 14'}
preferences['RR6']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '10', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 10'}
preferences['RR7']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '12', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 12'}
preferences['RR8']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '13', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 13'}
preferences['RR9']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '14', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 14'}
preferences['RR10']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['RR11']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['RR12']      = {'SrcStudyLabel': 'Session5', 'SrcSeriesLabel': '12', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['RR13']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['RR14']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['RR15']      = {'SrcStudyLabel': 'Session5', 'SrcSeriesLabel': '12', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['RD1']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '2', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgAsrName': ' 2'}
preferences['RD2']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '4', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgAsrName': ' 4'}
preferences['RD3']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 65, 'TxtToAddToTrgAsrName': ' 5'}
preferences['RD4']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session6', 'TrgSeriesLabel': '3', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 8, 'TxtToAddToTrgAsrName': ' 6_3'}
preferences['RD5']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session6', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 78, 'TxtToAddToTrgAsrName': ' 6_5'}
preferences['RD6']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'RTSTRUCT', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': 18, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '10', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 21, 'TxtToAddToTrgAsrName': ' 10'}
preferences['SR1']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '4', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 4'}
preferences['SR2']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '10', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 10'}
preferences['SR3']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 5'}
preferences['SR4']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '11', 'TrgAsrMod': 'RTSTRUCT', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 11'}
preferences['SR5']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '14', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 14'}
preferences['SR6']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '10', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 10'}
preferences['SR7']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '12', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 12'}
preferences['SR8']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '13', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 13'}
preferences['SR9']       = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session4', 'TrgSeriesLabel': '14', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 14'}
preferences['SR10']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['SR11']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['SR12']      = {'SrcStudyLabel': 'Session5', 'SrcSeriesLabel': '12', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session3', 'TrgSeriesLabel': '6', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 3_6'}
preferences['SR13']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '11', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['SR14']      = {'SrcStudyLabel': 'Session4', 'SrcSeriesLabel': '13', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['SR15']      = {'SrcStudyLabel': 'Session5', 'SrcSeriesLabel': '12', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgStudyLabel': 'Session1', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgAsrName': ' 1_5'}
preferences['SD1']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '2', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgAsrName': ' 2'}
preferences['SD2']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '4', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgAsrName': ' 4'}
preferences['SD3']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session2', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 65, 'TxtToAddToTrgAsrName': ' 5'}
preferences['SD4']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session6', 'TrgSeriesLabel': '3', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 8, 'TxtToAddToTrgAsrName': ' 6_3'}
preferences['SD5']       = {'SrcStudyLabel': 'Session2', 'SrcSeriesLabel': '2', 'SrcAsrMod': 'SEG', 'SrcAsrName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgStudyLabel': 'Session6', 'TrgSeriesLabel': '5', 'TrgAsrMod': 'SEG', 'TrgAsrName': None, 'TrgRoiName': None, 'TrgSliceNum': 78, 'TxtToAddToTrgAsrName': ' 6_5'}

##########################################################################################
############################## DYNAMIC PREFERENCES MODULES ###############################
dynamic = {}
