# This file is an automatically generated pypref preferences file. 

__pypref_version__ = '3.1.0' 

##########################################################################################
###################################### PREFERENCES #######################################
preferences = {}
preferences['XnatUrl']   = 'http://10.1.1.20'
preferences['ProjId']    = 'NCITA_TEST'
preferences['SubjLabel'] = 'TCGA-BB-A5HY'
preferences['RR1']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session2', 'TrgScanId': '4', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 4'}
preferences['RR2']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '10', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 10'}
preferences['RR3']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session2', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 5'}
preferences['RR4']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '11', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 11'}
preferences['RR5']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '14', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 14'}
preferences['RR6']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '10', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 10'}
preferences['RR7']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '12', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 12'}
preferences['RR8']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '13', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 13'}
preferences['RR9']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '14', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 14'}
preferences['RR10']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['RR11']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['RR12']      = {'SrcExpLabel': 'Session5', 'SrcScanId': '12', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['RR13']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['RR14']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['RR15']      = {'SrcExpLabel': 'Session5', 'SrcScanId': '12', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['RD1']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '2', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgRoiColName': ' 2'}
preferences['RD2']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '4', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgRoiColName': ' 4'}
preferences['RD3']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 65, 'TxtToAddToTrgRoiColName': ' 5'}
preferences['RD4']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session6', 'TrgScanId': '3', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 8, 'TxtToAddToTrgRoiColName': ' 6_3'}
preferences['RD5']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session6', 'TrgScanId': '5', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 78, 'TxtToAddToTrgRoiColName': ' 6_5'}
preferences['RD6']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': 18, 'TrgExpLabel': 'Session4', 'TrgScanId': '10', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 21, 'TxtToAddToTrgRoiColName': ' 10'}
preferences['SR1']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session2', 'TrgScanId': '4', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 4'}
preferences['SR2']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '10', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 10'}
preferences['SR3']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Left eye CT', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session2', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 5'}
preferences['SR4']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '11', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 11'}
preferences['SR5']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '14', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 14'}
preferences['SR6']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '10', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 10'}
preferences['SR7']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '12', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 12'}
preferences['SR8']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '13', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 13'}
preferences['SR9']       = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '14', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 14'}
preferences['SR10']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['SR11']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['SR12']      = {'SrcExpLabel': 'Session5', 'SrcScanId': '12', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session3', 'TrgScanId': '6', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 3_6'}
preferences['SR13']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '11', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Ventricles', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['SR14']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['SR15']      = {'SrcExpLabel': 'Session5', 'SrcScanId': '12', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Left eye', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session1', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' 1_5'}
preferences['SD1']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '2', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgRoiColName': ' 2'}
preferences['SD2']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '4', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 6, 'TxtToAddToTrgRoiColName': ' 4'}
preferences['SD3']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session2', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 65, 'TxtToAddToTrgRoiColName': ' 5'}
preferences['SD4']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session6', 'TrgScanId': '3', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 8, 'TxtToAddToTrgRoiColName': ' 6_3'}
preferences['SD5']       = {'SrcExpLabel': 'Session2', 'SrcScanId': '2', 'SrcRoiColMod': 'SEG', 'SrcRoiColName': 'Right eye CT (single slice)', 'SrcRoiName': None, 'SrcSliceNum': 5, 'TrgExpLabel': 'Session6', 'TrgScanId': '5', 'TrgRoiColMod': 'SEG', 'TrgRoiColName': None, 'TrgRoiName': None, 'TrgSliceNum': 78, 'TxtToAddToTrgRoiColName': ' 6_5'}
preferences['RR16']      = {'SrcExpLabel': 'Session4', 'SrcScanId': '13', 'SrcRoiColMod': 'RTSTRUCT', 'SrcRoiColName': 'Nasal cavity', 'SrcRoiName': None, 'SrcSliceNum': None, 'TrgExpLabel': 'Session4', 'TrgScanId': '11', 'TrgRoiColMod': 'RTSTRUCT', 'TrgRoiColName': 'Ventricles', 'TrgRoiName': None, 'TrgSliceNum': None, 'TxtToAddToTrgRoiColName': ' Ser11 2021-03-26'}

##########################################################################################
############################## DYNAMIC PREFERENCES MODULES ###############################
dynamic = {}
